// <auto-generated />
namespace CrowdDesign.Infrastructure.SQLServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddUniqueConstrainsAndMaxLenghts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddUniqueConstrainsAndMaxLenghts));
        
        string IMigrationMetadata.Id
        {
            get { return "201506112349116_AddUniqueConstrainsAndMaxLenghts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
